import { test, expect } from '@playwright/test';
import { PAGES } from './constants';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

test.describe('MIDI Preview Tool', () => {
	// Test fixture paths (generated by TypeScript create-test-midi.ts)
	const testMidiPath = path.join(__dirname, 'fixtures', 'test-sample.mid');

	test.describe('Navigation and Initial State', () => {
		test('opens the MIDI preview tool page', async ({ page }) => {
			await page.goto(PAGES.TOOLS);
			await page.waitForSelector('html[data-e2e-hydrated="true"]');

			// Verify tools page loads
			await expect(page.getByRole('heading', { name: 'Available Tools' })).toBeVisible();

			// Verify MIDI Preview tool is available
			await expect(page.getByRole('heading', { name: 'MIDI Preview' })).toBeVisible();
			await expect(
				page.getByText('Preview and analyze MIDI files with track information and playback')
			).toBeVisible();

			await page.goto(PAGES.MIDI_PREVIEW);
			await expect(page).toHaveURL(PAGES.MIDI_PREVIEW);
			await expect(
				page.getByRole('heading', { name: 'MIDI Preview', level: 1 })
			).toBeVisible();
		});
	});

	test.describe('File Upload Functionality', () => {
		test('should upload and parse a valid MIDI file with notes', async ({ page }) => {
			await page.goto(PAGES.MIDI_PREVIEW);
			await page.waitForLoadState('networkidle');
			await page.waitForSelector('html[data-e2e-hydrated="true"]');

			// Upload file
			await page.setInputFiles('input[type="file"]', testMidiPath);

			// Verify file information is displayed
			await expect(page.getByRole('heading', { name: 'File Loaded' })).toBeVisible({
				timeout: 10000
			});
			await expect(page.getByText('test-sample.mid')).toBeVisible();

			// Verify file information section appears
			await expect(page.getByRole('heading', { name: 'File Information' })).toBeVisible();
			await expect(page.getByText('Format', { exact: true })).toBeVisible();
			await expect(page.getByText('Tracks', { exact: true })).toBeVisible();
			await expect(page.getByText('Total Notes', { exact: true })).toBeVisible();
			await expect(page.getByText('Duration', { exact: true })).toBeVisible();
			await expect(page.getByText('Tempo', { exact: true })).toBeVisible();
			await expect(page.getByText('BPM', { exact: true })).toBeVisible();

			// Verify track details section appears
			await expect(page.getByRole('heading', { name: 'Track Details' })).toBeVisible();
		});
	});
});
