import { test, expect } from '@playwright/test';
import { PAGES } from './constants';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

test.describe('MIDI Preview Tool', () => {
	// Test fixture paths (generated by TypeScript create-test-midi.ts)
	const testMidiPath = path.join(__dirname, 'fixtures', 'test-sample.mid');
	const emptyMidiPath = path.join(__dirname, 'fixtures', 'empty-sample.mid');
	const multiTrackMidiPath = path.join(__dirname, 'fixtures', 'multi-track-sample.mid');
	const invalidFilePath = path.join(__dirname, 'fixtures', 'invalid-file.txt');

	test.describe('Navigation and Initial State', () => {
		test('should navigate from tools page to MIDI preview', async ({ page }) => {
			await page.goto(PAGES.TOOLS);

			// Verify tools page loads
			await expect(page.getByRole('heading', { name: 'Available Tools' })).toBeVisible();

			// Verify MIDI Preview tool is available
			await expect(page.getByRole('heading', { name: 'MIDI Preview' })).toBeVisible();
			await expect(
				page.getByText('Preview and analyze MIDI files with track information and playback')
			).toBeVisible();

			// Click on MIDI Preview tool
			await page.getByRole('button', { name: 'Open Tool' }).nth(1).click();

			// Verify navigation to MIDI preview page
			await expect(page).toHaveURL(PAGES.MIDI_PREVIEW);
			await expect(
				page.getByRole('heading', { name: 'MIDI Preview', level: 1 })
			).toBeVisible();
		});

		test('should display initial upload interface', async ({ page }) => {
			await page.goto(PAGES.MIDI_PREVIEW);

			// Verify upload section
			await expect(
				page.getByRole('heading', { name: 'Upload MIDI File', level: 2 })
			).toBeVisible();
			await expect(
				page.getByRole('heading', { name: 'Upload MIDI File', level: 3 })
			).toBeVisible();
			await expect(page.getByText('Select a .mid file to preview')).toBeVisible();
			await expect(page.getByRole('button', { name: 'Choose File' })).toBeVisible();

			// Verify info section
			await expect(page.getByRole('heading', { name: 'About MIDI Preview' })).toBeVisible();
			await expect(
				page.getByText('This tool allows you to preview and analyze MIDI files')
			).toBeVisible();
		});

		test('should have working navigation back to tools', async ({ page }) => {
			await page.goto(PAGES.MIDI_PREVIEW);

			// Click back button
			await page.getByRole('button', { name: '← Back to Tools' }).click();

			// Verify navigation back to tools page
			await expect(page).toHaveURL(PAGES.TOOLS);
			await expect(page.getByRole('heading', { name: 'Tools', level: 1 })).toBeVisible();
		});
	});

	test.describe('File Upload Functionality', () => {
		test('should upload and parse a valid MIDI file with notes', async ({ page }) => {
			await page.goto(PAGES.MIDI_PREVIEW);

			// Upload file
			const fileChooserPromise = page.waitForEvent('filechooser');
			await page.getByRole('button', { name: 'Choose File' }).click();
			const fileChooser = await fileChooserPromise;
			await fileChooser.setFiles([testMidiPath]);

			// Verify success notification
			await expect(page.getByText('MIDI file loaded')).toBeVisible();
			await expect(page.getByText(/Found \d+ tracks with \d+ notes/)).toBeVisible();

			// Verify file information is displayed
			await expect(page.getByRole('heading', { name: 'File Loaded' })).toBeVisible();
			await expect(page.getByText('test-sample.mid')).toBeVisible();

			// Verify file information section appears
			await expect(page.getByRole('heading', { name: 'File Information' })).toBeVisible();
			await expect(page.getByText('Format')).toBeVisible();
			await expect(page.getByText('Tracks')).toBeVisible();
			await expect(page.getByText('Total Notes')).toBeVisible();
			await expect(page.getByText('Duration')).toBeVisible();
			await expect(page.getByText('Tempo')).toBeVisible();
			await expect(page.getByText('BPM')).toBeVisible();

			// Verify track details section appears
			await expect(page.getByRole('heading', { name: 'Track Details' })).toBeVisible();
		});

		test('should upload and parse an empty MIDI file', async ({ page }) => {
			await page.goto(PAGES.MIDI_PREVIEW);

			// Upload empty MIDI file
			const fileChooserPromise = page.waitForEvent('filechooser');
			await page.getByRole('button', { name: 'Choose File' }).click();
			const fileChooser = await fileChooserPromise;
			await fileChooser.setFiles([emptyMidiPath]);

			// Verify success notification for empty file
			await expect(page.getByText('MIDI file loaded')).toBeVisible();

			// Verify it shows 0 notes
			await expect(page.getByText('0 notes', { exact: false })).toBeVisible();
		});

		test('should upload and parse a multi-track MIDI file', async ({ page }) => {
			await page.goto(PAGES.MIDI_PREVIEW);

			// Upload multi-track MIDI file
			const fileChooserPromise = page.waitForEvent('filechooser');
			await page.getByRole('button', { name: 'Choose File' }).click();
			const fileChooser = await fileChooserPromise;
			await fileChooser.setFiles([multiTrackMidiPath]);

			// Verify success notification
			await expect(page.getByText('MIDI file loaded')).toBeVisible();

			// Verify file information shows multiple tracks
			await expect(page.getByRole('heading', { name: 'File Information' })).toBeVisible();

			// Should show format 1 (multi-track)
			await expect(page.locator('text=Format').locator('..').getByText('1')).toBeVisible();

			// Should show 2 tracks
			await expect(page.locator('text=Tracks').locator('..').getByText('2')).toBeVisible();

			// Verify track details section shows multiple tracks
			await expect(page.getByText('Track 1')).toBeVisible();
			await expect(page.getByText('Track 2')).toBeVisible();
		});

		test('should reject invalid file types with error message', async ({ page }) => {
			await page.goto(PAGES.MIDI_PREVIEW);

			// Try to upload invalid file
			const fileChooserPromise = page.waitForEvent('filechooser');
			await page.getByRole('button', { name: 'Choose File' }).click();
			const fileChooser = await fileChooserPromise;
			await fileChooser.setFiles([invalidFilePath]);

			// Verify error notification
			await expect(page.getByText('Invalid file type')).toBeVisible();
			await expect(page.getByText('Please select a valid MIDI file (.mid)')).toBeVisible();

			// Verify upload interface is still shown (file not accepted)
			await expect(page.getByRole('button', { name: 'Choose File' })).toBeVisible();
			await expect(page.getByText('Select a .mid file to preview')).toBeVisible();
		});

		test('should allow removing uploaded file', async ({ page }) => {
			await page.goto(PAGES.MIDI_PREVIEW);

			// Upload a file first
			const fileChooserPromise = page.waitForEvent('filechooser');
			await page.getByRole('button', { name: 'Choose File' }).click();
			const fileChooser = await fileChooserPromise;
			await fileChooser.setFiles([testMidiPath]);

			// Wait for upload to complete
			await expect(page.getByText('MIDI file loaded')).toBeVisible();
			await expect(page.getByRole('heading', { name: 'File Loaded' })).toBeVisible();

			// Click remove button
			await page.getByRole('button', { name: 'Remove' }).click();

			// Verify file is removed and upload interface is shown again
			await expect(
				page.getByRole('heading', { name: 'Upload MIDI File', level: 3 })
			).toBeVisible();
			await expect(page.getByText('Select a .mid file to preview')).toBeVisible();
			await expect(page.getByRole('button', { name: 'Choose File' })).toBeVisible();

			// Verify file information sections are no longer visible
			await expect(page.getByRole('heading', { name: 'File Information' })).not.toBeVisible();
			await expect(page.getByRole('heading', { name: 'Track Details' })).not.toBeVisible();
		});

		test('should allow choosing a different file', async ({ page }) => {
			await page.goto(PAGES.MIDI_PREVIEW);

			// Upload a file first
			let fileChooserPromise = page.waitForEvent('filechooser');
			await page.getByRole('button', { name: 'Choose File' }).click();
			let fileChooser = await fileChooserPromise;
			await fileChooser.setFiles([testMidiPath]);

			// Wait for upload to complete
			await expect(page.getByText('MIDI file loaded')).toBeVisible();
			await expect(page.getByText('test-sample.mid')).toBeVisible();

			// Click choose different file
			fileChooserPromise = page.waitForEvent('filechooser');
			await page.getByRole('button', { name: 'Choose Different File' }).click();
			fileChooser = await fileChooserPromise;
			await fileChooser.setFiles([emptyMidiPath]);

			// Verify new file is loaded
			await expect(page.getByText('MIDI file loaded')).toBeVisible();
			await expect(page.getByText('empty-sample.mid')).toBeVisible();
		});
	});

	test.describe('MIDI Data Display', () => {
		test.beforeEach(async ({ page }) => {
			await page.goto(PAGES.MIDI_PREVIEW);

			// Upload test MIDI file for each test
			const fileChooserPromise = page.waitForEvent('filechooser');
			await page.getByRole('button', { name: 'Choose File' }).click();
			const fileChooser = await fileChooserPromise;
			await fileChooser.setFiles([testMidiPath]);

			// Wait for upload to complete
			await expect(page.getByText('MIDI file loaded')).toBeVisible();
		});

		test('should display file format information', async ({ page }) => {
			// Verify format information is displayed
			await expect(
				page.locator('text=Format').locator('..').getByText(/^\d+$/)
			).toBeVisible();
		});

		test('should display track count', async ({ page }) => {
			// Verify track count is displayed
			await expect(
				page.locator('text=Tracks').locator('..').getByText(/^\d+$/)
			).toBeVisible();
		});

		test('should display note count', async ({ page }) => {
			// Verify note count is displayed
			await expect(
				page.locator('text=Total Notes').locator('..').getByText(/^\d+$/)
			).toBeVisible();
		});

		test('should display duration', async ({ page }) => {
			// Verify duration is displayed in MM:SS format
			await expect(
				page
					.locator('text=Duration')
					.locator('..')
					.getByText(/^\d+:\d{2}$/)
			).toBeVisible();
		});

		test('should display tempo information', async ({ page }) => {
			// Verify tempo is displayed
			await expect(page.getByText(/\d+ BPM/)).toBeVisible();
		});

		test('should display ticks per quarter', async ({ page }) => {
			// Verify ticks per quarter is displayed
			await expect(
				page.locator('text=Ticks per Quarter').locator('..').getByText(/^\d+$/)
			).toBeVisible();
		});

		test('should display track details', async ({ page }) => {
			// Verify track details section
			await expect(page.getByRole('heading', { name: 'Track Details' })).toBeVisible();

			// Verify at least one track is shown
			await expect(page.getByText(/Track \d+/)).toBeVisible();

			// Verify track information columns
			await expect(page.getByText('Channels')).toBeVisible();
			await expect(page.getByText('Instruments')).toBeVisible();
			await expect(page.getByText('Note Range')).toBeVisible();
		});
	});

	test.describe('Error Handling', () => {
		test('should handle corrupted MIDI file gracefully', async ({ page }) => {
			// Create a file that looks like MIDI but is corrupted
			await page.goto(PAGES.MIDI_PREVIEW);

			// This test would require a corrupted MIDI file fixture
			// For now, we test with the invalid text file which should be caught by file extension check
			const fileChooserPromise = page.waitForEvent('filechooser');
			await page.getByRole('button', { name: 'Choose File' }).click();
			const fileChooser = await fileChooserPromise;
			await fileChooser.setFiles([invalidFilePath]);

			// Verify error handling
			await expect(page.getByText('Invalid file type')).toBeVisible();
		});
	});

	test.describe('Responsive Design', () => {
		test('should work on mobile viewport', async ({ page }) => {
			// Set mobile viewport
			await page.setViewportSize({ width: 375, height: 667 });
			await page.goto(PAGES.MIDI_PREVIEW);

			// Verify mobile layout
			await expect(
				page.getByRole('heading', { name: 'MIDI Preview', level: 1 })
			).toBeVisible();
			await expect(page.getByRole('button', { name: 'Choose File' })).toBeVisible();

			// Test file upload on mobile
			const fileChooserPromise = page.waitForEvent('filechooser');
			await page.getByRole('button', { name: 'Choose File' }).click();
			const fileChooser = await fileChooserPromise;
			await fileChooser.setFiles([testMidiPath]);

			// Verify mobile display of information
			await expect(page.getByText('MIDI file loaded')).toBeVisible();
			await expect(page.getByRole('heading', { name: 'File Information' })).toBeVisible();
		});
	});

	test.describe('Accessibility', () => {
		test('should have proper heading hierarchy', async ({ page }) => {
			await page.goto(PAGES.MIDI_PREVIEW);

			// Verify heading levels are correct
			await expect(
				page.getByRole('heading', { level: 1, name: 'MIDI Preview' })
			).toBeVisible();
			await expect(
				page.getByRole('heading', { level: 2, name: 'Upload MIDI File' })
			).toBeVisible();
			await expect(
				page.getByRole('heading', { level: 3, name: 'About MIDI Preview' })
			).toBeVisible();
		});

		test('should have accessible buttons', async ({ page }) => {
			await page.goto(PAGES.MIDI_PREVIEW);

			// Verify buttons have proper roles and are accessible
			await expect(page.getByRole('button', { name: 'Choose File' })).toBeVisible();
			await expect(page.getByRole('button', { name: '← Back to Tools' })).toBeVisible();
		});

		test('should handle keyboard navigation', async ({ page }) => {
			await page.goto(PAGES.MIDI_PREVIEW);

			// Tab through the interface
			await page.keyboard.press('Tab'); // Should focus on "Back to Tools"
			await expect(page.getByRole('button', { name: '← Back to Tools' })).toBeFocused();

			// Continue tabbing to other interactive elements
			await page.keyboard.press('Tab');
			await page.keyboard.press('Tab'); // Should eventually reach "Choose File"
		});
	});
});
