config:
  dtxweb-infrastructure:cloudflareAccountId: 91ee89a03a31b5354a25c49228e4ab85
  dtxweb-infrastructure:accessEmail:
    secure: AAABABNVdcI0Z3NWFl3KW83CV6FkNQDkv+bFwEknuLSUUoEiZLjv67rjq7SAQ73CrWvJ4cBaow==
  dtxweb-infrastructure:cloudflareZoneId: e02478b46bce77a4729a6ec21b01009d
