secretsprovider: default
config:
  dtxweb-infrastructure:cloudflareAccountId: 91ee89a03a31b5354a25c49228e4ab85
  dtxweb-infrastructure:devicePostureRuleId: 414d3bb6-4927-43fd-94a9-d5c2e171d5b5
  dtxweb-infrastructure:accessEmail:
    secure: AAABABNVdcI0Z3NWFl3KW83CV6FkNQDkv+bFwEknuLSUUoEiZLjv67rjq7SAQ73CrWvJ4cBaow==
