name: Lint and Format

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}

      - name: Remove tsconfig
        run: rm packages/dtx-web/tsconfig.json

      - name: Build packages
        run: npm run build -w=@dtx/common

      - name: Run linting
        run: npm run lint

      - name: Run formatting check
        run: npx prettier --check .
